### ISSUE TITLE
Install ?

### ISSUE THREAD

**Issue by Dreadox** [juancarlospaco/cloudbet#1]
How can i install this? Like, what should i use to compile, and host it in my web host? Its just for fun, buut, i want to know how can i install it. I tried on Xammp, but it doesnt work. Btw, do you have a group on Discord or something ? Thanks in advance [ Clone ]

**Comment by juancarlospaco** [comment]
`nimble install cloudbet`

You need https://nim-lang.org

**Comment by Dreadox** [comment]
Do you have a discord sir ?

lun., 30 mai 2022, 00:55 Juan Carlos ***@***.***> a scris:

**Comment by juancarlospaco** [comment]
No.
